server:
  port: :8889
  version: 1.0

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database:
  username: root
  password: 123456
  charset: utf8mb4

redis:
  user_name: default
  address: 127.0.0.1:6379
  password:

etcd:
  address: 127.0.0.1:2379

services:
  jwc:
    name: jwc
    loadBalance: false
    addr:
      - 127.0.0.1:10002

domain:
  jwc:
    name: jwc