// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: jwc.proto

package jwc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"stunum" form:"stunum" uri:"stunum"
	StuNum string `protobuf:"bytes,1,opt,name=StuNum,proto3" json:"StuNum,omitempty"`
	// @inject_tag: json:"stupass" form:"stupass" uri:"stupass"
	StuPass string `protobuf:"bytes,2,opt,name=StuPass,proto3" json:"StuPass,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_jwc_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetStuNum() string {
	if x != nil {
		return x.StuNum
	}
	return ""
}

func (x *LoginRequest) GetStuPass() string {
	if x != nil {
		return x.StuPass
	}
	return ""
}

type GsSessionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"ges_session" form:"ges_session" uri:"ges_session"
	GesSession string `protobuf:"bytes,1,opt,name=GesSession,proto3" json:"GesSession,omitempty"`
	// @inject_tag: json:"code" form:"code" uri:"code"
	Code int64 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GsSessionResponse) Reset() {
	*x = GsSessionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GsSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GsSessionResponse) ProtoMessage() {}

func (x *GsSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GsSessionResponse.ProtoReflect.Descriptor instead.
func (*GsSessionResponse) Descriptor() ([]byte, []int) {
	return file_jwc_proto_rawDescGZIP(), []int{1}
}

func (x *GsSessionResponse) GetGesSession() string {
	if x != nil {
		return x.GesSession
	}
	return ""
}

func (x *GsSessionResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Emaphome_WEURequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GesSession string `protobuf:"bytes,1,opt,name=GesSession,proto3" json:"GesSession,omitempty"`
}

func (x *Emaphome_WEURequest) Reset() {
	*x = Emaphome_WEURequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emaphome_WEURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emaphome_WEURequest) ProtoMessage() {}

func (x *Emaphome_WEURequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emaphome_WEURequest.ProtoReflect.Descriptor instead.
func (*Emaphome_WEURequest) Descriptor() ([]byte, []int) {
	return file_jwc_proto_rawDescGZIP(), []int{2}
}

func (x *Emaphome_WEURequest) GetGesSession() string {
	if x != nil {
		return x.GesSession
	}
	return ""
}

type Emaphome_WEUResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Emaphome_WEU string `protobuf:"bytes,1,opt,name=Emaphome_WEU,json=EmaphomeWEU,proto3" json:"Emaphome_WEU,omitempty"`
	Code         int64  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *Emaphome_WEUResponse) Reset() {
	*x = Emaphome_WEUResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jwc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Emaphome_WEUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emaphome_WEUResponse) ProtoMessage() {}

func (x *Emaphome_WEUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emaphome_WEUResponse.ProtoReflect.Descriptor instead.
func (*Emaphome_WEUResponse) Descriptor() ([]byte, []int) {
	return file_jwc_proto_rawDescGZIP(), []int{3}
}

func (x *Emaphome_WEUResponse) GetEmaphome_WEU() string {
	if x != nil {
		return x.Emaphome_WEU
	}
	return ""
}

func (x *Emaphome_WEUResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_jwc_proto protoreflect.FileDescriptor

var file_jwc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6a, 0x77, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x0c, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x74, 0x75, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x75,
	0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x50, 0x61, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x74, 0x75, 0x50, 0x61, 0x73, 0x73, 0x22, 0x47, 0x0a,
	0x11, 0x47, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x47, 0x65, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x35, 0x0a, 0x13, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f,
	0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x47, 0x65, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x47, 0x65, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a,
	0x14, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d,
	0x65, 0x5f, 0x57, 0x45, 0x55, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x45, 0x6d, 0x61,
	0x70, 0x68, 0x6f, 0x6d, 0x65, 0x57, 0x45, 0x55, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x7f, 0x0a, 0x0a,
	0x4a, 0x77, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x47, 0x73, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47, 0x73, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55,
	0x12, 0x14, 0x2e, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d, 0x65, 0x5f, 0x57, 0x45, 0x55, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x45, 0x6d, 0x61, 0x70, 0x68, 0x6f, 0x6d,
	0x65, 0x5f, 0x57, 0x45, 0x55, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a,
	0x04, 0x6a, 0x77, 0x63, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_jwc_proto_rawDescOnce sync.Once
	file_jwc_proto_rawDescData = file_jwc_proto_rawDesc
)

func file_jwc_proto_rawDescGZIP() []byte {
	file_jwc_proto_rawDescOnce.Do(func() {
		file_jwc_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwc_proto_rawDescData)
	})
	return file_jwc_proto_rawDescData
}

var file_jwc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_jwc_proto_goTypes = []interface{}{
	(*LoginRequest)(nil),         // 0: LoginRequest
	(*GsSessionResponse)(nil),    // 1: GsSessionResponse
	(*Emaphome_WEURequest)(nil),  // 2: Emaphome_WEURequest
	(*Emaphome_WEUResponse)(nil), // 3: Emaphome_WEUResponse
}
var file_jwc_proto_depIdxs = []int32{
	0, // 0: JwcService.GetGsSession:input_type -> LoginRequest
	2, // 1: JwcService.GetEmaphome_WEU:input_type -> Emaphome_WEURequest
	1, // 2: JwcService.GetGsSession:output_type -> GsSessionResponse
	3, // 3: JwcService.GetEmaphome_WEU:output_type -> Emaphome_WEUResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_jwc_proto_init() }
func file_jwc_proto_init() {
	if File_jwc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GsSessionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emaphome_WEURequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Emaphome_WEUResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jwc_proto_goTypes,
		DependencyIndexes: file_jwc_proto_depIdxs,
		MessageInfos:      file_jwc_proto_msgTypes,
	}.Build()
	File_jwc_proto = out.File
	file_jwc_proto_rawDesc = nil
	file_jwc_proto_goTypes = nil
	file_jwc_proto_depIdxs = nil
}
