// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.23.2
// source: idl/wx.proto

package wx

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WxAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature string `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Nonce     string `protobuf:"bytes,3,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Echoster  string `protobuf:"bytes,4,opt,name=Echoster,proto3" json:"Echoster,omitempty"`
}

func (x *WxAccessRequest) Reset() {
	*x = WxAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_wx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxAccessRequest) ProtoMessage() {}

func (x *WxAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_wx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxAccessRequest.ProtoReflect.Descriptor instead.
func (*WxAccessRequest) Descriptor() ([]byte, []int) {
	return file_idl_wx_proto_rawDescGZIP(), []int{0}
}

func (x *WxAccessRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WxAccessRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WxAccessRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *WxAccessRequest) GetEchoster() string {
	if x != nil {
		return x.Echoster
	}
	return ""
}

type WxAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Echoster string `protobuf:"bytes,1,opt,name=Echoster,proto3" json:"Echoster,omitempty"`
	Code     int64  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *WxAccessResponse) Reset() {
	*x = WxAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_wx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxAccessResponse) ProtoMessage() {}

func (x *WxAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_wx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxAccessResponse.ProtoReflect.Descriptor instead.
func (*WxAccessResponse) Descriptor() ([]byte, []int) {
	return file_idl_wx_proto_rawDescGZIP(), []int{1}
}

func (x *WxAccessResponse) GetEchoster() string {
	if x != nil {
		return x.Echoster
	}
	return ""
}

func (x *WxAccessResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_idl_wx_proto protoreflect.FileDescriptor

var file_idl_wx_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x64, 0x6c, 0x2f, 0x77, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7f,
	0x0a, 0x0f, 0x57, 0x78, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x6f,
	0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x22,
	0x42, 0x0a, 0x10, 0x57, 0x78, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x45, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x32, 0x42, 0x0a, 0x09, 0x57, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x35, 0x0a, 0x0e, 0x57, 0x65, 0x43, 0x68, 0x61, 0x74, 0x43, 0x61, 0x6c, 0x6c, 0x42, 0x61,
	0x63, 0x6b, 0x12, 0x10, 0x2e, 0x57, 0x78, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x57, 0x78, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x05, 0x5a, 0x03, 0x77, 0x78, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_wx_proto_rawDescOnce sync.Once
	file_idl_wx_proto_rawDescData = file_idl_wx_proto_rawDesc
)

func file_idl_wx_proto_rawDescGZIP() []byte {
	file_idl_wx_proto_rawDescOnce.Do(func() {
		file_idl_wx_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_wx_proto_rawDescData)
	})
	return file_idl_wx_proto_rawDescData
}

var file_idl_wx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idl_wx_proto_goTypes = []interface{}{
	(*WxAccessRequest)(nil),  // 0: WxAccessRequest
	(*WxAccessResponse)(nil), // 1: WxAccessResponse
}
var file_idl_wx_proto_depIdxs = []int32{
	0, // 0: WxService.WeChatCallBack:input_type -> WxAccessRequest
	1, // 1: WxService.WeChatCallBack:output_type -> WxAccessResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_wx_proto_init() }
func file_idl_wx_proto_init() {
	if File_idl_wx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_wx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_wx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_wx_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_wx_proto_goTypes,
		DependencyIndexes: file_idl_wx_proto_depIdxs,
		MessageInfos:      file_idl_wx_proto_msgTypes,
	}.Build()
	File_idl_wx_proto = out.File
	file_idl_wx_proto_rawDesc = nil
	file_idl_wx_proto_goTypes = nil
	file_idl_wx_proto_depIdxs = nil
}
